// This file is generated by `example-generator`. Do not edit manually.

import factorial from '../assets/examples/factorial.val?raw';
import fibonacci from '../assets/examples/fibonacci.val?raw';
import hoc from '../assets/examples/hoc.val?raw';
import loop from '../assets/examples/loop.val?raw';
import newton from '../assets/examples/newton.val?raw';
import primes from '../assets/examples/primes.val?raw';
import strings from '../assets/examples/strings.val?raw';

const EXAMPLES = {
  factorial: factorial,
  fibonacci: fibonacci,
  hoc: hoc,
  loop: loop,
  newton: newton,
  primes: primes,
  strings: strings
};

export default EXAMPLES;