// This file is generated by `example-generator`. Do not edit manually.

import factorial from '../assets/examples/factorial.val?raw';
import fibonacci from '../assets/examples/fibonacci.val?raw';
import hof from '../assets/examples/hof.val?raw';
import loop from '../assets/examples/loop.val?raw';
import math from '../assets/examples/math.val?raw';
import newton from '../assets/examples/newton.val?raw';
import primes from '../assets/examples/primes.val?raw';
import strings from '../assets/examples/strings.val?raw';

export const examples = {
  factorial: factorial,
  fibonacci: fibonacci,
  hof: hof,
  loop: loop,
  math: math,
  newton: newton,
  primes: primes,
  strings: strings
};
