/*
 Generated by typeshare 1.11.0
*/

export interface Range {
  start: number;
  end: number;
}

export interface AstNode {
  kind: string;
  range: Range;
  children: AstNode[];
}

export interface Error {
  message: string;
  range: Range;
}
