[package]
name = "val-wasm"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
val = { path = "../.." }
wasm-bindgen = "0.2.100"
